trigger: none

pool:
    vmImage: ubuntu-22.04

parameters:
    - name: 'TARGET_ENV'
      displayName: 'Target Environment'
      type: string
      default: 'uat'
      values:
          - 'dev'
          - 'uat'
    - name: 'AUTHORIZATION_TOKEN'
      displayName: 'The JWT token used to invoke APIs'
      type: string

    - name: 'dashboard'
      displayName: 'Run dashboard tests'
      type: boolean
      default: true
    
    - name: 'VIRTUAL_USERS_ENV'
      displayName: 'Number of virtual users (1 - 100 000)'
      type: number
      default: 3
    - name: 'SCENARIO_TYPE_ENV'
      displayName: 'Scenario type (if empty, it will execute all)'
      type: string
      default: ''
      values:
          - ''
          - 'rampingArrivalRate'
          - 'perVuIterations'
    
    - name: 'SCENARIO_RAMP_STAGE_NUMBER_ENV'
      displayName: 'rampingArrivalRate scenario: Number of ramping stages (min: 3)'
      type: number
      default: 3
    - name: 'SCENARIO_RAMP_TIME_UNIT_ENV'
      displayName: 'rampingArrivalRate scenario: The duration (seconds) of a single stage'
      type: number
      default: 1
    
    - name: 'SCENARIO_PER_VU_EXECUTIONS_ENV'
      displayName: 'perVuIterations scenario: the number of executions which each user will perform'
      type: number
      default: 1
    - name: 'SCENARIO_PER_VU_DURATION_ENV'
      displayName: 'perVuIterations scenario: the maximum number of seconds to wait for a single iteration'
      type: number
      default: 10
    
    - name: 'THRESHOLDS_API_MAX_AVG_MS_ENV'
      displayName: 'Max AVG duration applied as default to single API tests'
      type: number
      default: 500
    - name: 'THRESHOLDS_API_MAX_P90_MS_ENV'
      displayName: 'Max P90 duration applied as default to single API tests'
      type: number
      default: 800
    - name: 'THRESHOLDS_API_MAX_P95_MS_ENV'
      displayName: 'Max P95 duration applied as default to single API tests'
      type: number
      default: 1000
    
    - name: 'THRESHOLDS_FE_PAGE_MAX_P95_MS_ENV'
      displayName: 'Max P95 duration applied as default to FE page tests'
      type: number
      default: 1000
    - name: 'THRESHOLDS_FE_PAGE_MAX_P90_MS_ENV'
      displayName: 'Max P90 duration applied as default to FE page tests'
      type: number
      default: 2500
    - name: 'THRESHOLDS_FE_PAGE_MAX_P95_MS_ENV'
      displayName: 'Max P95 duration applied as default to FE page tests'
      type: number
      default: 3000

variables:
  testFolders: [$[parameters['dashboard']? 'dashboard': '']]

steps:
    - script: |
          docker pull grafana/k6:latest
      displayName: Pull k6 image
    - ${{each testFolder in variables.testFolders}}:
      - scripts: |
          docker run -i \
            --name ksixtests \
            --user $UID \
            -v $(pwd):/app \
            --workdir "/app" \
            -e TARGET_ENV=${{ parameters.TARGET_ENV }} \
            -e AUTHORIZATION_TOKEN=${{ parameters.AUTHORIZATION_TOKEN }} \
            -e VIRTUAL_USERS_ENV=${{ parameters.VIRTUAL_USERS_ENV }} \
            -e SCENARIO_TYPE_ENV=${{ parameters.SCENARIO_TYPE_ENV }} \
            -e SCENARIO_RAMP_STAGE_NUMBER_ENV=${{ parameters.SCENARIO_RAMP_STAGE_NUMBER_ENV }} \
            -e SCENARIO_RAMP_TIME_UNIT_ENV=${{ parameters.SCENARIO_RAMP_TIME_UNIT_ENV }} \
            -e SCENARIO_PER_VU_EXECUTIONS_ENV=${{ parameters.SCENARIO_PER_VU_EXECUTIONS_ENV }} \
            -e SCENARIO_PER_VU_DURATION_ENV=${{ parameters.SCENARIO_PER_VU_DURATION_ENV }} \
            grafana/k6:latest \
            /app/runAll.sh ${{ parameters.TARGET_ENV }} ${{ testFolder }}
        displayName: "Run k6 tests in folder: ${{ testFolder }}"
      - task: PublishTestResults@2
        displayName: "Publishing results of k6 tests in folder: ${{ testFolder }}"
        inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '/app/result/**/*-result.xml'
            searchFolder: '$(System.DefaultWorkingDirectory)'
            failTaskOnFailedTests: true
